import { 
	GOLD_KULLAQ_1,
	GOLD_KULLAQ_2,
	GOLD_KULLAQ_3,
	GOLD_KULLAQ_4,
	GOLD_KULLAQ_5,
	GOLD_KULLAQ_6,
	GOLD_SUMAQ_2,
	GOLD_SUMAQ_3,
	GOLD_SUMAQ_4,
	GOLD_SUMAQ_5,
	GOLD_SUMAQ_6,
	GOLD_LLURAK_2,
	GOLD_LLURAK_3,
	GOLD_LLURAK_4,
	GOLD_LLURAK_5,
	GOLD_LLURAK_6,
  EXPERIENCE_1,
  EXPERIENCE_2,
  PRODUCT_1,
  PRODUCT_2
} from "../assets/images"

import { Tent, ReviewIT, Promotion, Reserve, Experience,Product, NotificationIT } from "./interfaces"

export const experiencesData:Experience[] = [
  {
    id:1,
    categoryId:1,
    category: { id:1, name:"BambuExtreme", createdAt: new Date(), updatedAt: new Date() },
    header: "Experiencia Extrema",
    name:"Canotaje",
    description:"La mejor experiencia alrededor de Lunahuana.",
    price: 100,
    duration: 90,
    images: [EXPERIENCE_1,EXPERIENCE_2],
    status: "ACTIVE",
    limit_age: 18,
    qtypeople: 10,
    suggestions: ["Llevar ropa comoda","Llevar bloqueador","Llevar gorra"],
    custom_price: [ { dateFrom: new Date(), dateTo: new Date(), price:10 } ],
    createdAt: new Date(2024,5,28,12,0,0,0),
    updatedAt: new Date()
  },
  {
    id:2,
    categoryId:1,
    category: { id:1, name:"BambuExtreme", createdAt: new Date(), updatedAt: new Date() },
    header: "Deporte Extremo",
    name:"Cuatrimoto",
    description:"La mejor experiencia alrededor de Lunahuana.",
    price: 50,
    duration: 90,
    images: [EXPERIENCE_1,EXPERIENCE_2],
    status: "ACTIVE",
    limit_age: 18,
    qtypeople: 10,
    suggestions: ["Llevar ropa comoda","Llevar bloqueador","Llevar gorra"],
    custom_price: [ { dateFrom: new Date(), dateTo: new Date(), price:10 } ],
    createdAt: new Date(2024,5,28,12,0,0,0),
    updatedAt: new Date()
  }
]

export const productsData:Product[] = [
  {
    id: 1,
    categoryId:1,
    category:{ id:1, name:"BambuFood", createdAt: new Date(), updatedAt: new Date() },
    name: "Pizza",
    description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nec purus feugiat, molestie ipsum et, consequat nibh. Etiam non.",
    price: 100,
    images: [PRODUCT_1],
    stock: 10,
    custom_price: [ { dateFrom: new Date(), dateTo: new Date(), price:90 } ],
    status:"ACTIVE",
    createdAt: new Date(2024,5,28,12,0,0,0),
    updatedAt: new Date()
  },
  {
    id: 2,
    categoryId:1,
    category:{ id:1, name:"BambuFood", createdAt: new Date(), updatedAt: new Date() },
    name: "Vino",
    description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nec purus feugiat, molestie ipsum et, consequat nibh. Etiam non.",
    price: 100,
    images: [PRODUCT_2],
    stock: 10,
    custom_price: [ { dateFrom: new Date(), dateTo: new Date(), price:80 } ],
    status:"ACTIVE",
    createdAt: new Date(2024,5,28,12,0,0,0),
    updatedAt: new Date()
  }
]


export const notificationsData: NotificationIT[] = [
  {
    id:1,
    type:"I",
    title:"Reservation Confirmed",
    preview:"Your Reserve have been confirmed.",
    description:"Your Reserve have been confirmed.",
    date:"2024-07-12",
  },

  {
    id:2,
    type:"S",
    title:"Reservation Confirmed",
    preview:"Your Reserve have been confirmed.",
    description:"Your Reserve have been confirmed.",
    date:"2024-07-12",
  },

  {
    id:3,
    type:"E",
    title:"Reservation Confirmed",
    preview:"Your Reserve have been confirmed.",
    description:"Your Reserve have been confirmed.",
    date:"2024-07-12",
  },

]


export const tentsData:Tent[] = [
  {
    id: 1,
    header: "Tent 1",
    title: "Gold Kullaq",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nec purus feugiat, molestie ipsum et, consequat nibh. Etiam non.",
    images:[
      GOLD_KULLAQ_2,
      GOLD_KULLAQ_3,
      GOLD_KULLAQ_4,
      GOLD_KULLAQ_5,
      GOLD_KULLAQ_6,
    ],
    qtypeople:2,
    qtykids:2,
    price:100,
    services: {
      wifi: true,
      parking: true,
      pool: true,
      breakfast: true,
      lunch: true,
      dinner: true,
      spa: true,
      bar: true,
      hotwater: true,
      airconditioning: true,
      grill:true,
    },
    custom_price: [ { dateFrom: new Date(2024,6,14,0,0,0,0), dateTo: new Date(2024,7,20,0,0,0,0), price:80 } ],
    status: "ACTIVE",
    createdAt:new Date(),
    updatedAt: new Date()
  },
  {
    id: 2,
    header: "Tent 1",
    title: "Gold Sumaq",
    price:100,
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nec purus feugiat, molestie ipsum et, consequat nibh. Etiam non.",
    images:[
      GOLD_SUMAQ_2,
      GOLD_SUMAQ_3,
      GOLD_SUMAQ_4,
      GOLD_SUMAQ_5,
      GOLD_SUMAQ_6,
    ],
    qtypeople:2,
    qtykids:2,
    services: {
      wifi: true,
      parking: true,
      pool: true,
      breakfast: true,
      lunch: false,
      dinner: true,
      spa: true,
      bar: false,
      hotwater: false,
      airconditioning: true,
      grill:false,
    },
    custom_price: [ { dateFrom: new Date(2024,6,14,0,0,0,0), dateTo: new Date(2024,7,20,0,0,0,0), price:80 } ],
    status: "ACTIVE",
    createdAt:new Date(),
    updatedAt: new Date()
  },
  {
    id: 3,
    header: "Tent 1",
    title: "Suite Llurak",
    price:100,
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nec purus feugiat, molestie ipsum et, consequat nibh. Etiam non.",
    images:[
      GOLD_LLURAK_2,
      GOLD_LLURAK_3,
      GOLD_LLURAK_4,
      GOLD_LLURAK_5,
      GOLD_LLURAK_6,
    ],
    services: {
      wifi: true,
      parking: true,
      pool: true,
      breakfast: true,
      lunch: true,
      dinner: true,
      spa: true,
      bar: true,
      hotwater: true,
      airconditioning: true,
      grill:false,
    },
    qtypeople:2,
    qtykids:2,
    custom_price: [ { dateFrom: new Date(2024,6,14,0,0,0,0), dateTo: new Date(2024,7,20,0,0,0,0), price:60 } ],
    status: "ACTIVE",
    createdAt:new Date(),
    updatedAt: new Date()
  },
  {
    id: 4,
    header: "Tent 1",
    title: "Suite Sallary",
    price:100,
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nec purus feugiat, molestie ipsum et, consequat nibh. Etiam non.",
    images:[
      GOLD_SUMAQ_2,
      GOLD_SUMAQ_3,
      GOLD_SUMAQ_4,
      GOLD_SUMAQ_5,
      GOLD_SUMAQ_6,
    ],
    services: {
      wifi: true,
      parking: true,
      pool: true,
      breakfast: true,
      lunch: true,
      dinner: true,
      spa: true,
      bar: true,
      hotwater: true,
      airconditioning: true,
      grill:false,
    },
    qtypeople:2,
    qtykids:2,
    custom_price: [ { dateFrom: new Date(2024,6,14,0,0,0,0), dateTo: new Date(2024,7,20,0,0,0,0), price:60 } ],
    status: "ACTIVE",
    createdAt:new Date(),
    updatedAt: new Date()
  },
  {
    id: 5,
    header: "Tent 1",
    title: "Suite Wayra",
    price:100,
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nec purus feugiat, molestie ipsum et, consequat nibh. Etiam non.",
    images:[
      GOLD_KULLAQ_2,
      GOLD_KULLAQ_3,
      GOLD_KULLAQ_4,
      GOLD_KULLAQ_5,
      GOLD_KULLAQ_6,
    ],
    services: {
      wifi: true,
      parking: true,
      pool: true,
      breakfast: true,
      lunch: true,
      dinner: true,
      spa: true,
      bar: true,
      hotwater: true,
      airconditioning: true,
      grill:false,
    },
    qtypeople:2,
    qtykids:2,
    custom_price: [ { dateFrom: new Date(2024,6,14,0,0,0,0), dateTo: new Date(2024,7,20,0,0,0,0), price:60 } ],
    status: "ACTIVE",
    createdAt:new Date(),
    updatedAt: new Date()
  },
  {
    id: 6,
    header: "Tent 1",
    title: "Suite Yana",
    price:100,
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nec purus feugiat, molestie ipsum et, consequat nibh. Etiam non.",
    images:[
      GOLD_KULLAQ_2,
      GOLD_KULLAQ_3,
      GOLD_KULLAQ_4,
      GOLD_KULLAQ_5,
      GOLD_KULLAQ_6,
    ],
    services: {
      wifi: true,
      parking: true,
      pool: true,
      breakfast: true,
      lunch: true,
      dinner: true,
      spa: true,
      bar: false,
      hotwater: false,
      airconditioning: false,
      grill:false,
    },
    qtypeople:2,
    qtykids:2,
    custom_price: [ { dateFrom: new Date(2024,6,14,0,0,0,0), dateTo: new Date(2024,7,20,0,0,0,0), price:60 } ],
    status: "ACTIVE",
    createdAt:new Date(),
    updatedAt: new Date()
  },
]


export const ReservesData:Reserve[] = [
  {
    id: 1,
    userId:1,
    qtypeople:2,
    qtykids:2,
    tents:[ { idTent:1, name:"Bambu Kullaq", price:100, quantity: 1 } ],
    products:[ { idProduct:1, name:"Pizza", price:100, quantity: 1 } ],
    experiences:[ { idExperience:1, name:"Cuatirmoto", price:100, quantity: 1 } ],
    dateFrom: new Date(2024,5,28,12,0,0,0),
    dateTo: new Date(2024,5,30,12,0,0,0),
    dateSale: new Date(),
    promotionId: 0,
    price_is_calculated: true,
    discountCodeId: 0,
    netImport: 300,
    discount: 0,
    grossImport: 300,
    canceled_reason: "",
    canceled_status: false,
    paymentStatus:"PENDING",
    aditionalPeople:2,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: 2,
    userId:1,
    qtypeople:2,
    qtykids:2,
    tents:[ { idTent:1, name:"Bambu Kullaq", price:100, quantity: 1 } ],
    products:[ { idProduct:1, name:"Pizza", price:100, quantity: 1 } ],
    experiences:[ { idExperience:1, name:"Cuatirmoto", price:100, quantity: 1 } ],
    dateFrom: new Date(2024,5,28,12,0,0,0),
    dateTo: new Date(2024,5,30,12,0,0,0),
    dateSale: new Date(),
    promotionId: 0,
    price_is_calculated: true,
    discountCodeId: 0,
    netImport: 300,
    discount: 10,
    grossImport: 270,
    canceled_reason: "",
    canceled_status: false,
    paymentStatus:"PENDING",
    aditionalPeople:2,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: 3,
    userId:1,
    qtypeople:2,
    qtykids:2,
    tents:[ { idTent:1, name:"Bambu Kullaq", price:100, quantity: 1 } ],
    products:[ { idProduct:1, name:"Pizza", price:100, quantity: 1 } ],
    experiences:[ { idExperience:1, name:"Cuatirmoto", price:100, quantity: 1 } ],
    dateFrom: new Date(2024,5,28,12,0,0,0),
    dateTo: new Date(2024,5,30,12,0,0,0),
    dateSale: new Date(),
    promotionId: 0,
    price_is_calculated: true,
    discountCodeId: 0,
    netImport: 300,
    discount: 10,
    grossImport: 270,
    canceled_reason: "",
    canceled_status: false,
    paymentStatus:"PENDING",
    aditionalPeople:2,
    createdAt: new Date(),
    updatedAt: new Date()
  },
]


export const reviewsData:ReviewIT[] = [
  {
    id:1,
    name: "Marco Antonio Venturo Cosme",
    title: "Excelente experiencia",
    review: "Un lugar muy bonito, tranquilo y relajante, excelente atención, tiene todas las comodidades, es un campamento de lujo, tiene piscina, puedes comprar bebidas, comida y snack, una experiencia muy bonita. Recomendado.",
    stars: 4,
    date: "01-03-2024",
    profile_image: "https://ashallendesign.ams3.cdn.digitaloceanspaces.com/rMbsGOyK6i1KjNkbXff8qLohzM1nWQA8HNGwHF0J.png",
    images: [GOLD_KULLAQ_1,GOLD_KULLAQ_2,GOLD_KULLAQ_3]
  },
  {
    id:2,
    name: "Marco Antonio Venturo Cosme",
    title: "Excelente experiencia",
    review: "Un lugar muy bonito, tranquilo y relajante, excelente atención, tiene todas las comodidades, es un campamento de lujo, tiene piscina, puedes comprar bebidas, comida y snack, una experiencia muy bonita. Recomendado.",
    stars: 4,
    date: "01-03-2024",
    profile_image: "https://ashallendesign.ams3.cdn.digitaloceanspaces.com/rMbsGOyK6i1KjNkbXff8qLohzM1nWQA8HNGwHF0J.png",
    images: [GOLD_KULLAQ_1,GOLD_KULLAQ_2,GOLD_KULLAQ_3]
  },
  {
    id:3,
    name: "Marco Antonio Venturo Cosme",
    title: "Excelente experiencia",
    review: "Un lugar muy bonito, tranquilo y relajante, excelente atención, tiene todas las comodidades, es un campamento de lujo, tiene piscina, puedes comprar bebidas, comida y snack, una experiencia muy bonita. Recomendado.",
    stars: 4,
    date: "01-03-2024",
    profile_image: "https://ashallendesign.ams3.cdn.digitaloceanspaces.com/rMbsGOyK6i1KjNkbXff8qLohzM1nWQA8HNGwHF0J.png",
    images: [GOLD_KULLAQ_1,GOLD_KULLAQ_2,GOLD_KULLAQ_3]
  },
  {
    id:4,
    name: "Marco Antonio Venturo Cosme",
    title: "Excelente experiencia",
    review: "Un lugar muy bonito, tranquilo y relajante, excelente atención, tiene todas las comodidades, es un campamento de lujo, tiene piscina, puedes comprar bebidas, comida y snack, una experiencia muy bonita. Recomendado.",
    stars: 4,
    date: "01-03-2024",
    profile_image: "https://ashallendesign.ams3.cdn.digitaloceanspaces.com/rMbsGOyK6i1KjNkbXff8qLohzM1nWQA8HNGwHF0J.png",
    images: [GOLD_KULLAQ_1,GOLD_KULLAQ_2,GOLD_KULLAQ_3]
  },
  {
    id:5,
    name: "Marco Antonio Venturo Cosme",
    title: "Excelente experiencia",
    review: "Un lugar muy bonito, tranquilo y relajante, excelente atención, tiene todas las comodidades, es un campamento de lujo, tiene piscina, puedes comprar bebidas, comida y snack, una experiencia muy bonita. Recomendado.",
    stars: 4,
    date: "01-03-2024",
    profile_image: "https://ashallendesign.ams3.cdn.digitaloceanspaces.com/rMbsGOyK6i1KjNkbXff8qLohzM1nWQA8HNGwHF0J.png",
    images: [GOLD_KULLAQ_1,GOLD_KULLAQ_2,GOLD_KULLAQ_3]
  },
  {
    id:5,
    name: "Marco Antonio Venturo Cosme",
    title: "Excelente experiencia",
    review: "Un lugar muy bonito, tranquilo y relajante, excelente atención, tiene todas las comodidades, es un campamento de lujo, tiene piscina, puedes comprar bebidas, comida y snack, una experiencia muy bonita. Recomendado.",
    stars: 4,
    date: "01-03-2024",
    profile_image: "https://ashallendesign.ams3.cdn.digitaloceanspaces.com/rMbsGOyK6i1KjNkbXff8qLohzM1nWQA8HNGwHF0J.png",
    images: [GOLD_KULLAQ_1,GOLD_KULLAQ_2,GOLD_KULLAQ_3]
  },
  {
    id:6,
    name: "Marco Antonio Venturo Cosme",
    title: "Excelente experiencia",
    review: "Un lugar muy bonito, tranquilo y relajante, excelente atención, tiene todas las comodidades, es un campamento de lujo, tiene piscina, puedes comprar bebidas, comida y snack, una experiencia muy bonita. Recomendado.",
    stars: 4,
    date: "01-03-2024",
    profile_image: "https://ashallendesign.ams3.cdn.digitaloceanspaces.com/rMbsGOyK6i1KjNkbXff8qLohzM1nWQA8HNGwHF0J.png",
    images: [GOLD_KULLAQ_1,GOLD_KULLAQ_2,GOLD_KULLAQ_3]
  },
  {
    id:7,
    name: "Marco Antonio Venturo Cosme",
    title: "Excelente experiencia",
    review: "Un lugar muy bonito, tranquilo y relajante, excelente atención, tiene todas las comodidades, es un campamento de lujo, tiene piscina, puedes comprar bebidas, comida y snack, una experiencia muy bonita. Recomendado.",
    stars: 4,
    date: "01-03-2024",
    profile_image: "https://ashallendesign.ams3.cdn.digitaloceanspaces.com/rMbsGOyK6i1KjNkbXff8qLohzM1nWQA8HNGwHF0J.png",
    images: [GOLD_KULLAQ_1,GOLD_KULLAQ_2,GOLD_KULLAQ_3]
  },
]

export const promotionsData:Promotion[] = [
  {
    id: 1,
    title: "Promotion 1",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nec purus feugiat, molestie ipsum et, consequat nibh. Etiam non.",
    images: [GOLD_KULLAQ_2],
    expiredDate: new Date(),
    status: "ACTIVE",
    qtypeople: 2,
    qtykids:2,
    netImport: 100,
    discount: 20,
    grossImport:80,
    stock:1000,
    idtents: [ { id:1, label:"Gold Kullaq", qty:1, price:100 } ],
    idproducts: [ { id:1, label:"Pizza", qty:1, price:20 } ], 
    idexperiences: [ { id:2, label:"Cuatrimoto", qty:1, price:20 } ], 
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: 2,
    title: "Promotion 2",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nec purus feugiat, molestie ipsum et, consequat nibh. Etiam non.",
    images: [GOLD_KULLAQ_2],
    expiredDate: new Date(),
    status: "ACTIVE",
    qtypeople: 2,
    qtykids:2,
    netImport: 100,
    discount: 20,
    grossImport:80,
    stock:1000,
    idtents: [ { id:1, label:"Gold Kullaq", qty:1, price:100 } ],
    idproducts: [ { id:1, label:"Pizza", qty:1, price:20 } ], 
    idexperiences: [ { id:2, label:"Cuatrimoto", qty:1, price:20 } ], 
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: 3,
    title: "Promotion 3",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nec purus feugiat, molestie ipsum et, consequat nibh. Etiam non.",
    images: [GOLD_KULLAQ_2],
    expiredDate: new Date(),
    status: "ACTIVE",
    qtypeople: 2,
    qtykids:2,
    netImport: 100,
    discount: 20,
    grossImport:80,
    stock:1000,
    idtents: [ { id:1, label:"Gold Kullaq", qty:1, price:100 } ],
    idproducts: [ { id:1, label:"Pizza", qty:1, price:20 } ], 
    idexperiences: [ { id:2, label:"Cuatrimoto", qty:1, price:20 } ], 
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: 4,
    title: "Promotion 3",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nec purus feugiat, molestie ipsum et, consequat nibh. Etiam non.",
    images: [GOLD_KULLAQ_2],
    expiredDate: new Date(),
    status: "ACTIVE",
    qtypeople: 2,
    qtykids:2,
    netImport: 100,
    discount: 20,
    grossImport:80,
    stock:1000,
    idtents: [ { id:1, label:"Gold Kullaq", qty:1, price:100 } ],
    idproducts: [ { id:1, label:"Pizza", qty:1, price:20 } ], 
    idexperiences: [ { id:2, label:"Cuatrimoto", qty:1, price:20 } ], 
    createdAt: new Date(),
    updatedAt: new Date()
  },
]
